### ISSUE TITLE
域名迁移

### ISSUE THREAD

**Issue by fz6m** [opq-osc/opq-helper#5]
由于 `opqbot.com` 域名即将过期，并无资金续费，以下是计划废止日程：

### 第一阶段：临时重定向

时间：2024/04/14 ~ 2024/04/30

|域名|行为|
|:-:|:-:|
|`opqbot.com`|跳转到 GitHub Pages 文档站 (302)|
|`wiki.opqbot.com`|跳转到 GitHub Pages 文档站 (302)|
|`docs.opqbot.com`|跳转到 GitHub Pages 文档站 (302)|
|`yui.opqbot.com`|无变化|
|`botoy.opqbot.com`|无变化|
|`mahiro.opqbot.com`|无变化|

### 第二阶段：永久重定向

时间：2024/05/01 ~ 2024/05/30

|域名|行为|
|:-:|:-:|
|`opqbot.com`|跳转到 GitHub Pages 文档站 (301)|
|`wiki.opqbot.com`|跳转到 GitHub Pages 文档站 (301)|
|`docs.opqbot.com`|跳转到 GitHub Pages 文档站 (301)|
|`yui.opqbot.com`|跳转到对应项目 GitHub 页面 (301)|
|`botoy.opqbot.com`|跳转到对应项目 GitHub 页面 (301)|
|`mahiro.opqbot.com`|跳转到对应项目 GitHub 页面 (301)|

### 第三阶段：废止

时间：2024/06/01 ~

|域名|行为|
|:-:|:-:|
|`opqbot.com`|停用|
|`wiki.opqbot.com`|停用|
|`docs.opqbot.com`|停用|
|`yui.opqbot.com`|停用|
|`botoy.opqbot.com`|停用|
|`mahiro.opqbot.com`|停用|

### 迁移

请对应仓库 owner 在 **`2024/05/01`** 前进行以下迁移计划之一：

1. 不再维护：去除项目中相关的 url 链接，关闭站点，archive 仓库。

2. 继续维护：去除项目中相关的 url 链接，改为 GitHub Pages url 或部署到自己的站点 url 。

cc @mcoo / @xiyaowong

**Comment by fz6m** [comment]
如需续费，80 r / year ，转到我 Q 即可。

如要转移，请先在供应商处确认可以接收，并在此 issue 回复转移时间精确时间与联系方式（因为转移代码只有 1 小时有效期），在指定时间内我会发送该代码至对应邮箱，届时完成接收即可。

**Comment by xiyaowong** [comment]
先不转移吧，懒得解析。

**Comment by fz6m** [comment]
![CleanShot 2024-04-18 at 9  13 07](https://github.com/opq-osc/opq-helper/assets/59400654/fe7e0b1a-01fb-46f8-8eb7-2f8a9d9e7e8f)
